package quoi.api.skyblock.dungeon.map.utils

import quoi.QuoiMod.logger
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.resources.ResourceLocation
import net.minecraft.tags.FluidTags
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.state.BlockState
import net.minecraft.world.level.block.state.properties.Property
import kotlin.jvm.optionals.getOrNull

object LegacyIdMapper {
    val legacyBlockIdMap = mapOf(
        "minecraft:air" to 0,
        "minecraft:stone" to 1,
        "minecraft:granite" to 1,
        "minecraft:polished_granite" to 1,
        "minecraft:diorite" to 1,
        "minecraft:polished_diorite" to 1,
        "minecraft:andesite" to 1,
        "minecraft:polished_andesite" to 1,
        "minecraft:grass_block" to 2,
        "minecraft:dirt" to 3,
        "minecraft:coarse_dirt" to 3,
        "minecraft:podzol" to 3,
        "minecraft:cobblestone" to 4,
        "minecraft:oak_planks" to 5,
        "minecraft:spruce_planks" to 5,
        "minecraft:birch_planks" to 5,
        "minecraft:jungle_planks" to 5,
        "minecraft:acacia_planks" to 5,
        "minecraft:dark_oak_planks" to 5,
        "minecraft:oak_sapling" to 6,
        "minecraft:spruce_sapling" to 6,
        "minecraft:birch_sapling" to 6,
        "minecraft:jungle_sapling" to 6,
        "minecraft:acacia_sapling" to 6,
        "minecraft:dark_oak_sapling" to 6,
        "minecraft:bedrock" to 7,
        "minecraft:water" to Pair(8, 9),
        "minecraft:lava" to Pair(10, 11),
        "minecraft:sand" to 12,
        "minecraft:red_sand" to 12,
        "minecraft:gravel" to 13,
        "minecraft:gold_ore" to 14,
        "minecraft:iron_ore" to 15,
        "minecraft:coal_ore" to 16,
        "minecraft:oak_log" to 17,
        "minecraft:spruce_log" to 17,
        "minecraft:birch_log" to 17,
        "minecraft:jungle_log" to 17,
        "minecraft:oak_wood" to 17,
        "minecraft:spruce_wood" to 17,
        "minecraft:birch_wood" to 17,
        "minecraft:jungle_wood" to 17,
        "minecraft:oak_leaves" to 18,
        "minecraft:spruce_leaves" to 18,
        "minecraft:birch_leaves" to 18,
        "minecraft:jungle_leaves" to 18,
        "minecraft:sponge" to 19,
        "minecraft:wet_sponge" to 19,
        "minecraft:glass" to 20,
        "minecraft:lapis_ore" to 21,
        "minecraft:lapis_block" to 22,
        "minecraft:dispenser" to 23,
        "minecraft:sandstone" to 24,
        "minecraft:chiseled_sandstone" to 24,
        "minecraft:cut_sandstone" to 24,
        "minecraft:note_block" to 25,
        "minecraft:red_bed" to 26,
        "minecraft:powered_rail" to 27,
        "minecraft:detector_rail" to 28,
        "minecraft:sticky_piston" to 29,
        "minecraft:cobweb" to 30,
        "minecraft:dead_bush" to Pair(31, 32),
        "minecraft:grass" to 31,
        "minecraft:fern" to 31,
        "minecraft:piston" to 33,
        "minecraft:piston_head" to 34,
        "minecraft:white_wool" to 35,
        "minecraft:orange_wool" to 35,
        "minecraft:magenta_wool" to 35,
        "minecraft:light_blue_wool" to 35,
        "minecraft:yellow_wool" to 35,
        "minecraft:lime_wool" to 35,
        "minecraft:pink_wool" to 35,
        "minecraft:gray_wool" to 35,
        "minecraft:light_gray_wool" to 35,
        "minecraft:cyan_wool" to 35,
        "minecraft:purple_wool" to 35,
        "minecraft:blue_wool" to 35,
        "minecraft:brown_wool" to 35,
        "minecraft:green_wool" to 35,
        "minecraft:red_wool" to 35,
        "minecraft:black_wool" to 35,
        "minecraft:moving_piston" to 36,
        "minecraft:dandelion" to 37,
        "minecraft:poppy" to 38,
        "minecraft:blue_orchid" to 38,
        "minecraft:allium" to 38,
        "minecraft:azure_bluet" to 38,
        "minecraft:red_tulip" to 38,
        "minecraft:orange_tulip" to 38,
        "minecraft:white_tulip" to 38,
        "minecraft:pink_tulip" to 38,
        "minecraft:oxeye_daisy" to 38,
        "minecraft:brown_mushroom" to 39,
        "minecraft:red_mushroom" to 40,
        "minecraft:gold_block" to 41,
        "minecraft:iron_block" to 42,
        "minecraft:smooth_stone_slab[type=double]" to 43,
        "minecraft:sandstone_slab[type=double]" to 43,
        "minecraft:petrified_oak_slab[type=double]" to 43,
        "minecraft:cobblestone_slab[type=double]" to 43,
        "minecraft:brick_slab[type=double]" to 43,
        "minecraft:stone_brick_slab[type=double]" to 43,
        "minecraft:nether_brick_slab[type=double]" to 43,
        "minecraft:quartz_slab[type=double]" to 43,
        "minecraft:smooth_stone" to 43,
        "minecraft:smooth_sandstone" to 43,
        "minecraft:smooth_quartz" to 43,
        "minecraft:smooth_stone_slab[type=bottom]" to 44,
        "minecraft:sandstone_slab[type=bottom]" to 44,
        "minecraft:petrified_oak_slab[type=bottom]" to 44,
        "minecraft:cobblestone_slab[type=bottom]" to 44,
        "minecraft:brick_slab[type=bottom]" to 44,
        "minecraft:stone_brick_slab[type=bottom]" to 44,
        "minecraft:nether_brick_slab[type=bottom]" to 44,
        "minecraft:quartz_slab[type=bottom]" to 44,
        "minecraft:smooth_stone_slab[type=top]" to 44,
        "minecraft:sandstone_slab[type=top]" to 44,
        "minecraft:petrified_oak_slab[type=top]" to 44,
        "minecraft:cobblestone_slab[type=top]" to 44,
        "minecraft:brick_slab[type=top]" to 44,
        "minecraft:stone_brick_slab[type=top]" to 44,
        "minecraft:nether_brick_slab[type=top]" to 44,
        "minecraft:quartz_slab[type=top]" to 44,
        "minecraft:bricks" to 45,
        "minecraft:tnt" to 46,
        "minecraft:bookshelf" to 47,
        "minecraft:mossy_cobblestone" to 48,
        "minecraft:obsidian" to 49,
        "minecraft:wall_torch" to 50,
        "minecraft:torch" to 50,
        "minecraft:fire" to 51,
        "minecraft:spawner" to 52,
        "minecraft:oak_stairs" to 53,
        "minecraft:chest" to 54,
        "minecraft:redstone_wire" to 55,
        "minecraft:diamond_ore" to 56,
        "minecraft:diamond_block" to 57,
        "minecraft:crafting_table" to 58,
        "minecraft:wheat" to 59,
        "minecraft:farmland" to 60,
        "minecraft:furnace" to 61,
        "minecraft:sign" to 63,
        "minecraft:oak_door" to 64,
        "minecraft:ladder" to 65,
        "minecraft:rail" to 66,
        "minecraft:cobblestone_stairs" to 67,
        "minecraft:wall_sign" to 68,
        "minecraft:lever" to 69,
        "minecraft:stone_pressure_plate" to 70,
        "minecraft:iron_door" to 71,
        "minecraft:oak_pressure_plate" to 72,
        "minecraft:redstone_ore[lit=false]" to 73,
        "minecraft:redstone_ore[lit=true]" to 74,
        "minecraft:redstone_wall_torch[lit=false]" to 75,
        "minecraft:redstone_torch[lit=false]" to 75,
        "minecraft:redstone_wall_torch[lit=true]" to 76,
        "minecraft:redstone_torch[lit=true]" to 76,
        "minecraft:stone_button" to 77,
        "minecraft:snow" to 78,
        "minecraft:ice" to 79,
        "minecraft:snow_block" to 80,
        "minecraft:cactus" to 81,
        "minecraft:clay" to 82,
        "minecraft:sugar_cane" to 83,
        "minecraft:jukebox" to 84,
        "minecraft:oak_fence" to 85,
        "minecraft:carved_pumpkin" to 86,
        "minecraft:netherrack" to 87,
        "minecraft:soul_sand" to 88,
        "minecraft:glowstone" to 89,
        "minecraft:nether_portal" to 90,
        "minecraft:jack_o_lantern" to 91,
        "minecraft:cake" to 92,
        "minecraft:repeater[powered=false]" to 93,
        "minecraft:repeater[powered=true]" to 94,
        "minecraft:white_stained_glass" to 95,
        "minecraft:orange_stained_glass" to 95,
        "minecraft:magenta_stained_glass" to 95,
        "minecraft:light_blue_stained_glass" to 95,
        "minecraft:yellow_stained_glass" to 95,
        "minecraft:lime_stained_glass" to 95,
        "minecraft:pink_stained_glass" to 95,
        "minecraft:gray_stained_glass" to 95,
        "minecraft:light_gray_stained_glass" to 95,
        "minecraft:cyan_stained_glass" to 95,
        "minecraft:purple_stained_glass" to 95,
        "minecraft:blue_stained_glass" to 95,
        "minecraft:brown_stained_glass" to 95,
        "minecraft:green_stained_glass" to 95,
        "minecraft:red_stained_glass" to 95,
        "minecraft:black_stained_glass" to 95,
        "minecraft:oak_trapdoor" to 96,
        "minecraft:infested_stone" to 97,
        "minecraft:infested_cobblestone" to 97,
        "minecraft:infested_stone_bricks" to 97,
        "minecraft:infested_mossy_stone_bricks" to 97,
        "minecraft:infested_cracked_stone_bricks" to 97,
        "minecraft:infested_chiseled_stone_bricks" to 97,
        "minecraft:stone_bricks" to 98,
        "minecraft:mossy_stone_bricks" to 98,
        "minecraft:cracked_stone_bricks" to 98,
        "minecraft:chiseled_stone_bricks" to 98,
        "minecraft:brown_mushroom_block" to 99,
        "minecraft:mushroom_stem" to Pair(99, 100),
        "minecraft:red_mushroom_block" to 100,
        "minecraft:iron_bars" to 101,
        "minecraft:glass_pane" to 102,
        "minecraft:melon" to 103,
        "minecraft:pumpkin_stem" to 104,
        "minecraft:melon_stem" to 105,
        "minecraft:vine" to 106,
        "minecraft:oak_fence_gate" to 107,
        "minecraft:brick_stairs" to 108,
        "minecraft:stone_brick_stairs" to 109,
        "minecraft:mycelium[snowy=false]" to 110,
        "minecraft:lily_pad" to 111,
        "minecraft:nether_bricks" to 112,
        "minecraft:nether_brick_fence" to 113,
        "minecraft:nether_brick_stairs" to 114,
        "minecraft:nether_wart" to 115,
        "minecraft:enchanting_table" to 116,
        "minecraft:brewing_stand" to 117,
        "minecraft:cauldron" to 118,
        "minecraft:end_portal" to 119,
        "minecraft:end_portal_frame" to 120,
        "minecraft:end_stone" to 121,
        "minecraft:dragon_egg" to 122,
        "minecraft:redstone_lamp[lit=false]" to 123,
        "minecraft:redstone_lamp[lit=true]" to 124,
        "minecraft:oak_slab[type=double]" to 125,
        "minecraft:spruce_slab[type=double]" to 125,
        "minecraft:birch_slab[type=double]" to 125,
        "minecraft:jungle_slab[type=double]" to 125,
        "minecraft:acacia_slab[type=double]" to 125,
        "minecraft:dark_oak_slab[type=double]" to 125,
        "minecraft:oak_slab[type=bottom]" to 126,
        "minecraft:spruce_slab[type=bottom]" to 126,
        "minecraft:birch_slab[type=bottom]" to 126,
        "minecraft:jungle_slab[type=bottom]" to 126,
        "minecraft:acacia_slab[type=bottom]" to 126,
        "minecraft:dark_oak_slab[type=bottom]" to 126,
        "minecraft:oak_slab[type=top]" to 126,
        "minecraft:spruce_slab[type=top]" to 126,
        "minecraft:birch_slab[type=top]" to 126,
        "minecraft:jungle_slab[type=top]" to 126,
        "minecraft:acacia_slab[type=top]" to 126,
        "minecraft:dark_oak_slab[type=top]" to 126,
        "minecraft:cocoa" to 127,
        "minecraft:sandstone_stairs" to 128,
        "minecraft:emerald_ore" to 129,
        "minecraft:ender_chest" to 130,
        "minecraft:tripwire_hook" to 131,
        "minecraft:tripwire" to 132,
        "minecraft:emerald_block" to 133,
        "minecraft:spruce_stairs" to 134,
        "minecraft:birch_stairs" to 135,
        "minecraft:jungle_stairs" to 136,
        "minecraft:command_block" to 137,
        "minecraft:beacon" to 138,
        "minecraft:cobblestone_wall" to 139,
        "minecraft:mossy_cobblestone_wall" to 139,
        "minecraft:flower_pot" to 140,
        "minecraft:potted_poppy" to 140,
        "minecraft:potted_dandelion" to 140,
        "minecraft:potted_oak_sapling" to 140,
        "minecraft:potted_spruce_sapling" to 140,
        "minecraft:potted_birch_sapling" to 140,
        "minecraft:potted_jungle_sapling" to 140,
        "minecraft:potted_red_mushroom" to 140,
        "minecraft:potted_brown_mushroom" to 140,
        "minecraft:potted_cactus" to 140,
        "minecraft:potted_dead_bush" to 140,
        "minecraft:potted_fern" to 140,
        "minecraft:potted_acacia_sapling" to 140,
        "minecraft:potted_dark_oak_sapling" to 140,
        "minecraft:potted_blue_orchid" to 140,
        "minecraft:potted_allium" to 140,
        "minecraft:carrots" to 141,
        "minecraft:potatoes" to 142,
        "minecraft:oak_button" to 143,
        "minecraft:skeleton_skull" to 144,
        "minecraft:skeleton_wall_skull" to 144,
        "minecraft:anvil" to 145,
        "minecraft:chipped_anvil" to 145,
        "minecraft:damaged_anvil" to 145,
        "minecraft:trapped_chest" to 146,
        "minecraft:light_weighted_pressure_plate" to 147,
        "minecraft:heavy_weighted_pressure_plate" to 148,
        "minecraft:comparator[powered=false]" to 149,
        "minecraft:comparator[powered=true]" to 150,
        "minecraft:daylight_detector[inverted=false]" to 151,
        "minecraft:redstone_block" to 152,
        "minecraft:nether_quartz_ore" to 153,
        "minecraft:hopper" to 154,
        "minecraft:quartz_block" to 155,
        "minecraft:chiseled_quartz_block" to 155,
        "minecraft:quartz_pillar[axis=y]" to 155,
        "minecraft:quartz_pillar[axis=x]" to 155,
        "minecraft:quartz_pillar[axis=z]" to 155,
        "minecraft:quartz_stairs" to 156,
        "minecraft:activator_rail" to 157,
        "minecraft:dropper" to 158,
        "minecraft:white_terracotta" to 159,
        "minecraft:orange_terracotta" to 159,
        "minecraft:magenta_terracotta" to 159,
        "minecraft:light_blue_terracotta" to 159,
        "minecraft:yellow_terracotta" to 159,
        "minecraft:lime_terracotta" to 159,
        "minecraft:pink_terracotta" to 159,
        "minecraft:gray_terracotta" to 159,
        "minecraft:light_gray_terracotta" to 159,
        "minecraft:cyan_terracotta" to 159,
        "minecraft:purple_terracotta" to 159,
        "minecraft:blue_terracotta" to 159,
        "minecraft:brown_terracotta" to 159,
        "minecraft:green_terracotta" to 159,
        "minecraft:red_terracotta" to 159,
        "minecraft:black_terracotta" to 159,
        "minecraft:white_stained_glass_pane" to 160,
        "minecraft:orange_stained_glass_pane" to 160,
        "minecraft:magenta_stained_glass_pane" to 160,
        "minecraft:light_blue_stained_glass_pane" to 160,
        "minecraft:yellow_stained_glass_pane" to 160,
        "minecraft:lime_stained_glass_pane" to 160,
        "minecraft:pink_stained_glass_pane" to 160,
        "minecraft:gray_stained_glass_pane" to 160,
        "minecraft:light_gray_stained_glass_pane" to 160,
        "minecraft:cyan_stained_glass_pane" to 160,
        "minecraft:purple_stained_glass_pane" to 160,
        "minecraft:blue_stained_glass_pane" to 160,
        "minecraft:brown_stained_glass_pane" to 160,
        "minecraft:green_stained_glass_pane" to 160,
        "minecraft:red_stained_glass_pane" to 160,
        "minecraft:black_stained_glass_pane" to 160,
        "minecraft:acacia_leaves" to 161,
        "minecraft:dark_oak_leaves" to 161,
        "minecraft:acacia_log" to 162,
        "minecraft:dark_oak_log" to 162,
        "minecraft:acacia_wood" to 162,
        "minecraft:dark_oak_wood" to 162,
        "minecraft:acacia_stairs" to 163,
        "minecraft:dark_oak_stairs" to 164,
        "minecraft:slime_block" to 165,
        "minecraft:barrier" to 166,
        "minecraft:iron_trapdoor" to 167,
        "minecraft:prismarine" to 168,
        "minecraft:prismarine_bricks" to 168,
        "minecraft:dark_prismarine" to 168,
        "minecraft:sea_lantern" to 169,
        "minecraft:hay_block" to 170,
        "minecraft:white_carpet" to 171,
        "minecraft:orange_carpet" to 171,
        "minecraft:magenta_carpet" to 171,
        "minecraft:light_blue_carpet" to 171,
        "minecraft:yellow_carpet" to 171,
        "minecraft:lime_carpet" to 171,
        "minecraft:pink_carpet" to 171,
        "minecraft:gray_carpet" to 171,
        "minecraft:light_gray_carpet" to 171,
        "minecraft:cyan_carpet" to 171,
        "minecraft:purple_carpet" to 171,
        "minecraft:blue_carpet" to 171,
        "minecraft:brown_carpet" to 171,
        "minecraft:green_carpet" to 171,
        "minecraft:red_carpet" to 171,
        "minecraft:black_carpet" to 171,
        "minecraft:terracotta" to 172,
        "minecraft:coal_block" to 173,
        "minecraft:packed_ice" to 174,
        "minecraft:sunflower" to 175,
        "minecraft:lilac" to 175,
        "minecraft:tall_grass" to 175,
        "minecraft:large_fern" to 175,
        "minecraft:rose_bush" to 175,
        "minecraft:peony" to 175,
        "minecraft:white_banner" to 176,
        "minecraft:white_wall_banner" to 177,
        "minecraft:daylight_detector[inverted=true]" to 178,
        "minecraft:red_sandstone" to 179,
        "minecraft:chiseled_red_sandstone" to 179,
        "minecraft:cut_red_sandstone" to 179,
        "minecraft:red_sandstone_stairs" to 180,
        "minecraft:red_sandstone_slab[type=double]" to 181,
        "minecraft:smooth_red_sandstone" to 181,
        "minecraft:red_sandstone_slab[type=bottom]" to 182,
        "minecraft:red_sandstone_slab[type=top]" to 182,
        "minecraft:spruce_fence_gate" to 183,
        "minecraft:birch_fence_gate" to 184,
        "minecraft:jungle_fence_gate" to 185,
        "minecraft:dark_oak_fence_gate" to 186,
        "minecraft:acacia_fence_gate" to 187,
        "minecraft:spruce_fence" to 188,
        "minecraft:birch_fence" to 189,
        "minecraft:jungle_fence" to 190,
        "minecraft:dark_oak_fence" to 191,
        "minecraft:acacia_fence" to 192,
        "minecraft:spruce_door" to 193,
        "minecraft:birch_door" to 194,
        "minecraft:jungle_door" to 195,
        "minecraft:acacia_door" to 196,
        "minecraft:dark_oak_door" to 197,
        "minecraft:end_rod" to 198,
        "minecraft:chorus_plant" to 199,
        "minecraft:chorus_flower" to 200,
        "minecraft:purpur_block" to 201,
        "minecraft:purpur_pillar" to 202,
        "minecraft:purpur_stairs" to 203,
        "minecraft:purpur_slab[type=double]" to 204,
        "minecraft:purpur_slab[type=bottom]" to 205,
        "minecraft:purpur_slab[type=top]" to 205,
        "minecraft:end_stone_bricks" to 206,
        "minecraft:beetroots" to 207,
        "minecraft:grass_path" to 208,
        "minecraft:end_gateway" to 209,
        "minecraft:repeating_command_block" to 210,
        "minecraft:chain_command_block" to 211,
        "minecraft:frosted_ice" to 212,
        "minecraft:magma_block" to 213,
        "minecraft:nether_wart_block" to 214,
        "minecraft:red_nether_bricks" to 215,
        "minecraft:bone_block" to 216,
        "minecraft:structure_void" to 217,
        "minecraft:observer" to 218,
        "minecraft:white_shulker_box" to 219,
        "minecraft:orange_shulker_box" to 220,
        "minecraft:magenta_shulker_box" to 221,
        "minecraft:light_blue_shulker_box" to 222,
        "minecraft:yellow_shulker_box" to 223,
        "minecraft:lime_shulker_box" to 224,
        "minecraft:pink_shulker_box" to 225,
        "minecraft:gray_shulker_box" to 226,
        "minecraft:light_gray_shulker_box" to 227,
        "minecraft:cyan_shulker_box" to 228,
        "minecraft:purple_shulker_box" to 229,
        "minecraft:blue_shulker_box" to 230,
        "minecraft:brown_shulker_box" to 231,
        "minecraft:green_shulker_box" to 232,
        "minecraft:red_shulker_box" to 233,
        "minecraft:black_shulker_box" to 234,
        "minecraft:white_glazed_terracotta" to 235,
        "minecraft:orange_glazed_terracotta" to 236,
        "minecraft:magenta_glazed_terracotta" to 237,
        "minecraft:light_blue_glazed_terracotta" to 238,
        "minecraft:yellow_glazed_terracotta" to 239,
        "minecraft:lime_glazed_terracotta" to 240,
        "minecraft:pink_glazed_terracotta" to 241,
        "minecraft:gray_glazed_terracotta" to 242,
        "minecraft:light_gray_glazed_terracotta" to 243,
        "minecraft:cyan_glazed_terracotta" to 244,
        "minecraft:purple_glazed_terracotta" to 245,
        "minecraft:blue_glazed_terracotta" to 246,
        "minecraft:brown_glazed_terracotta" to 247,
        "minecraft:green_glazed_terracotta" to 248,
        "minecraft:red_glazed_terracotta" to 249,
        "minecraft:black_glazed_terracotta" to 250,
        "minecraft:white_concrete" to 251,
        "minecraft:orange_concrete" to 251,
        "minecraft:magenta_concrete" to 251,
        "minecraft:light_blue_concrete" to 251,
        "minecraft:yellow_concrete" to 251,
        "minecraft:lime_concrete" to 251,
        "minecraft:pink_concrete" to 251,
        "minecraft:gray_concrete" to 251,
        "minecraft:light_gray_concrete" to 251,
        "minecraft:cyan_concrete" to 251,
        "minecraft:purple_concrete" to 251,
        "minecraft:blue_concrete" to 251,
        "minecraft:brown_concrete" to 251,
        "minecraft:green_concrete" to 251,
        "minecraft:red_concrete" to 251,
        "minecraft:black_concrete" to 251,
        "minecraft:white_concrete_powder" to 252,
        "minecraft:orange_concrete_powder" to 252,
        "minecraft:magenta_concrete_powder" to 252,
        "minecraft:light_blue_concrete_powder" to 252,
        "minecraft:yellow_concrete_powder" to 252,
        "minecraft:lime_concrete_powder" to 252,
        "minecraft:pink_concrete_powder" to 252,
        "minecraft:gray_concrete_powder" to 252,
        "minecraft:light_gray_concrete_powder" to 252,
        "minecraft:cyan_concrete_powder" to 252,
        "minecraft:purple_concrete_powder" to 252,
        "minecraft:blue_concrete_powder" to 252,
        "minecraft:brown_concrete_powder" to 252,
        "minecraft:green_concrete_powder" to 252,
        "minecraft:red_concrete_powder" to 252,
        "minecraft:black_concrete_powder" to 252,
        "minecraft:structure_block" to 255
    )

    val block2Legacy = mutableMapOf<Block, Int>()
    val block2PropertyMatch = mutableMapOf<Block, MutableSet<PropertyRequirement>>()

    init {
        legacyBlockIdMap.forEach { (key, legacyValue) ->
            val legacyId = when (legacyValue) {
                is Int -> legacyValue
                is Pair<*, *> -> legacyValue.first as? Int ?: return@forEach
                else -> return@forEach
            }

            val rawKey = key.substringBefore('[')
            val block = BuiltInRegistries.BLOCK.getOptional(ResourceLocation.parse(rawKey)).getOrNull() ?: return@forEach

            if ('[' !in key) {
                block2Legacy[block] = legacyId
                return@forEach
            }

            val rawProperties = key.substringAfter('[').substringBefore(']')
            val propMap = rawProperties.split(',').associate { entry ->
                val (name, value) = entry.split('=')
                val prop = block.stateDefinition.getProperty(name) ?: return@forEach
                val parsed = prop.getValue(value).getOrNull() ?: return@forEach
                prop to parsed
            }

            val requirement = PropertyRequirement(block, propMap, legacyId)
            block2PropertyMatch.getOrPut(block) { mutableSetOf() }.add(requirement)
        }
    }

    data class PropertyRequirement(
        val block: Block,
        val properties: Map<Property<*>, Comparable<*>>,
        val legacyId: Int
    )

    fun getId(state: BlockState): Int {
        if (state.isAir) return 0

        val fluid = state.fluidState
        if (!fluid.isEmpty) {
            return when {
                fluid.`is`(FluidTags.WATER) -> if (fluid.isSource) 9 else 8
                fluid.`is`(FluidTags.LAVA) -> if (fluid.isSource) 11 else 10
                else -> -1
            }
        }

        // Direct block mapping
        block2Legacy[state.block]?.let { return it }

        // Match against property requirements
        val matchers = block2PropertyMatch[state.block] ?: return -1
        matchers.firstOrNull { req ->
            req.properties.all { (prop, value) ->
                state.getValue(prop) == value
            }
        }?.legacyId?.let { return it }

        logger.warn("[LegacyID] Unmatched state: ${state.block} → ${state.values}")
        return -1
    }

}